name: Deploy to Kubernetes

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ojhdev/portfolio:${{ github.sha }} .
        docker tag ojhdev/portfolio:${{ github.sha }} ojhdev/portfolio:latest

    - name: Push Docker image
      run: |
        docker push ojhdev/portfolio:${{ github.sha }}
        docker push ojhdev/portfolio:latest

    - name: Decode kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > $HOME/.kube/config
        
    - name: Install Google Cloud SDK and GKE Auth Plugin
      run: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo apt-get install -y apt-transport-https ca-certificates gnupg
        sudo apt-get update && sudo apt-get install -y google-cloud-sdk
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|ojhdev/portfolio:latest|ojhdev/portfolio:${{ github.sha }}|g" deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl rollout status deployment/portfolio